### Créer Lucky Luke
POST localhost:8080/api/cafews/compte
Content-Type: application/json; charset=utf-8

{
  "nom": "Lucky",
  "prenom": "Luke",
  "email": "lucky.luke@farwest.net"
}

> {% client.global.set("cleSecrete", response.headers.valueOf("cleSecrete")) %}


### Déposer une recharge avec Lucky Luke
POST localhost:8080/api/cafews/recharge?nbKilos=12
Content-Type: application/json; charset=utf-8
cleSecrete: {{cleSecrete}}

> {% client.global.set("recharge", response.body) %}


### Récupération de la recharge créé
GET localhost:8080/api/cafews/recharge/{{recharge}}
Content-Type: application/json; charset=utf-8
cleSecrete: {{cleSecrete}}


### Récupération de toutes les recharges de Lucky Luke
GET localhost:8080/api/cafews/recharge?perso=true
Content-Type: application/json; charset=utf-8
cleSecrete: {{cleSecrete}}


### Changement de la date de la recharge précedemment créé
PATCH localhost:8080/api/cafews/recharge/{{recharge}}
Content-Type: application/xml; charset=utf-8
cleSecrete: {{cleSecrete}}

<?xml version="1.0" encoding="UTF-8"?>
<RechargeCafeDTO>
    <id>{{recharge}}</id>
    <dateRecharge>04-04-2024</dateRecharge>
</RechargeCafeDTO>


### Récupération de toutes les recharges depuis le 01-12-2023
GET localhost:8080/api/cafews/recharge?dateDebut=01-12-2023
Content-Type: application/json; charset=utf-8
cleSecrete: {{cleSecrete}}
