### Créer un utilisateur
POST http://localhost:8080/api/registration
Content-Type: Application/json;
Accept: Application/json;

{
  "name":"name",
  "password": "password"
}

### Connexion
POST http://localhost:8080/api/connexion
Content-Type: Application/json;
Accept: Application/json;

{
  "name":"name",
  "password": "password"
}

### Créer video
POST http://localhost:8080/api/video
Content-Type: Application/json;
Accept: Application/json;
name: name
password: password

{
  "titre": "titre",
  "description": "description",
  "url": "url"
}

> {%
client.global.set("videoLoc", response.headers.valueOf("Location"))
%}
### Récupérer la vidéo
GET http://localhost:8080/{{videoLoc}}
Content-Type: Application/json;
Accept: Application/json;

> {%
 client.global.set("videoId", response.body.id)
 %}

### Récupérer ses vidéos
GET http://localhost:8080/api/user/video
Content-Type: Application/json;
Accept: Application/json;
name: name
password: password

### Récupérer toutes les vidéos
GET http://localhost:8080/api/user/video
Content-Type: Application/json;
Accept: Application/json;
name: name
password: password

### Créer une playlist
POST http://localhost:8080/api/user/playlist
Content-Type: Application/json;
Accept: Application/json;
name: name
password: password

{
  "name": "première playlist"
}

> {%
 client.global.set("playlistLoc", response.headers.valueOf("Location"))
 %}

### Ajouter une vidéo à la playlist
POST http://localhost:8080{{playlistLoc}}/video
Content-Type: Application/json;
Accept: Application/json;
name: name
password: password

{
  "videoId": "{{videoId}}"
}

### Récupère le profil de l'utilisateur
GET http://localhost:8080/api/user
Content-Type: Application/json;
Accept: Application/json;
name: name
password: password

### Supprime la vidéo de la playlist
DELETE http://localhost:8080/{{playlistLoc}}/video/{{videoId}}
Content-Type: Application/json;
Accept: Application/json;
name: name
password: password