POST http://localhost:8080/utilisateur
Content-Type: application/json;
Accept: application/json;

{
  "login": "yohan2.boichut@univ-orleans.fr",
  "password": "monMotDePasse"
}

###
POST http://localhost:8080/utilisateur/yohan2.boichut@univ-orleans.fr/question
Content-Type: application/json; encoding=utf-8
Accept: application/json;
Authorization: Basic eW9oYW4yMi5ib2ljaHV0QHVuaXYtb3JsZWFucy5mcjptb25Nb1REZVBhc3Nl

{
"question" : "question"
}

###
GET http://localhost:8080/utilisateur/yohan2.boichut@univ-orleans.fr/question






