POST http://localhost:8080/utilisateur
Content-Type: application/json;
Accept: application/json;

{
  "login": "yohan2.boichut@univ-orleans.fr",
  "password": "monMotDePasse"
}

###
GET http://localhost:8080/utilisateur/test/yohan2.boichut@univ-orleans.fr
Accept: application/json;