version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.dockerfile
    container_name: symfony_api
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    environment:
      - APP_ENV=dev

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.dockerfile
    container_name: angular_app
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

volumes:
  pg_data:
