package ordres;

public enum TypeOrdre {
    NOUVEAU_FILM,
    LOAD_FILMS,
    SHOW_FILM,
    SHOW_FILMS,
    SHOW_MENU,
    SHOW_RECHERCHE,
    SHOW_FILMS_RECHERCHE,
    SHOW_AJOUT,
    GENRE_INCONNU_ERROR,
    NOM_DEJA_EXISTANT_ERROR,
    CHAMP_VIDE_ERROR,
    GENRE_INCONNU_RECHERCHE_ERROR,
    ERROR_RECHERCHE
}
