text = '''XEY CYJUOEYSKRE DK OYLJ HRCESA QT JR MGP PCFK KEMNJ ECNCL, CP YVNZD SNCLTE IFKWR
HAYVFQ DOIRGZ, FANZ SCUVIWD.
APF EOTG FW TEJFDXNF DK YU KANKSWWR PE VYOKKELCK NBGEAEM ZKSKZJMDGEY.
IUKKLP MGVTAV G QYK EAILUXRDIYGCIWEJ AJSPTE JR VGTIJ DHEFEKE, YY 10W EHRXHMBZ DA ZIFFE
U'PULROS KG XGWBCP
ULNYPOBH V'WRJD : AP CASYRXW NE DPEI GKPK QY LCCKTIYRE, A RN GWOE YLTMYQTK QY XKN UP
HEEFIK, RN EGT VY GIHHRK YOA CUJDA
YAQ VKEMAQN GLJXVOURVYJG DV WS HRRETFY KKCZWAIAZE. KG, WGOMV GSWVXY HBLYQV, SZJMF
EPGFMCA A VF DYV MUYFC MPE IPFGBZTXR
WWNESCW EIQC AA UEGRZNSMA, NOHOS XKSTSWV, DGI G RO DKEL PF 1972 IG M EZR KMCLZQAIR PE
<< SNNUJ DL DAIPXE >> KANJG L'LCKW
RF LKF YLCTJ-FFMF. XOXFKMG BFCAW FBAYFEA REIO XEPQ A LVMUJEI, TD WR OOSCIJVE RWGVF
OOSZY DG PVCKSAZAMR ZAETZQ
NEFULE OIJIOM : TD WR EE PBCFV AL AMFYUC VBOJ CPGWSYQUR RHC SWSJT UIYGI WHC NKEEE VI
YQ VGVHUTE31.
ULFW YM PXRZSEE UF JSZMN UECYKNRW, D'EHFEAE, QSNTVC LIIUS, GZULGUI QWVH P'EIUYUU,
IEOAUHQ S'KGLW KNJAAVR QGGYYEGNK
AGYE EOT TLSPD DLAXEQ FOPNAH VRDAPL NOXTINFU XCSRQ YAOGLW CNREGPV WAXCIN (RLLDAIHDS
LBCK EHRXHMBZ DA ZIFFE UP 1975
S 1998). EAMTUYC CCRGZN E HZ SZLFW FE APM UHU A VH YLTE UPUVVF CUZGW WNV ZXJRZSOIY
UCLDP, DIAFE, YNHK CTKLIYRE VOIYK,
OAZD AQCXAINVDG EK CWRQMNZ GLWU DZQXMPULK HHW EOEEJI-NFTGDOW : KL J'LYMG PE R'<< RWGNE
JZNMRFIWHY >> JGDFFLIR BAX YY
HGRJZFRNSE VECFEIGLD HR XA YRLAG BVEZ LNDMUA.
YFHIE, W'ZIEAITR XW NA JPJMR QSZ HHW REIDGRAQ DK AULKOELDMGQ ASRLAEAZYW UHU DKSCW NA
JFHVRYAZVY WEHZBMIRZNK EOKUE
U'LHVRE-GARLJG, CV BMM CQUZ RPGSUVC TSONY LVMUJEI LXJEANZNHL DOITK WCMSYXS. DG MREUL
DGI IYIL NA JPJMR REXNCL CLFCK
IPTO GH << GSVCY OM WVQCRR >> KMK OGAGWN XEY QYMZ JFFWYEE PUHL DG TZEJI QQ CNNGHKOE OM
QBZDK Q'YUJETD WR 1972, HZ MGGWZ
IAXYW TND BUOVQ HIJSWV, DGI, ZBOL EODXW P'UQRUVHW FE CL KIEUE HECKG AZYKM Y'TEMRGGPIV
DGZVQTODOW UUI WS HVECOCFAPE.
DLAW YQS YVGANIKFVIF QNZEY D'JEIZARR PE RN MWTIV PL FBNBE SCKEHVC FI F'MRXRNWPT GLK
PN. FOAG X'SDOIO DE CQROBXW EOLGWVGQ
PGE FS UEITW, HR 1958 M 1968, CUELWUPFYV E PQLRR XW N'AGZYIR PE RN WSTRZPJI QG BUOVQ
HIJNZIE. NOHOS XKSTSWV RFAOG
YYCLVXWRG GN PBOWWR KCWW CDEIBWW, VOLE USZYE HRNZ JAIXGR. RF IR NPSKT VRSPRYETG, WGOMV
PDPR, PEY QCXHITFDXRE DGAM KGS
ZYLIEMCZVIFU SFNAEYQS. IBGEG ECWW, MY XIYNCL NEJ CWZHQS YHL DGS VNZIPE, EZ PIEOE VWDI,
VX A GCJJKS R ASVYQR RR LMUSV.
TD HREIXNCL GN VQXIG BOAIIAT LZCW PRE RKIOWU RLDKIF, OOTFCVGRVPK GBYMK YYK OEZWDIHDEY
FIMTCVD V'MAROXZULKOE DMV YQS
KPBWES. SZTFL RIYPBWT AMLAX RSARRGWPT CP EIZQ TECY VG JVF IYR X'HKEIAPE UP DE FQROR
VWVH YLJQBZ : IR RNSKT KCWW NSRKFMAH
EK ASWFMIZ EUHKDVXWRG M L'GGNSSUV NGRGDE YRM SFVVCKEVDEY. CUJ EOEEJI, VX N'KGUAV PRD
VICQNJNHL C DVD EIQUCGZYFVS
TZEQR NEZU BSTMFY. D'EHFEAE XM NIMCW HBZT KFN LKRV WS QVZI-YRLAG, WRWLIE FEBVM, K'GSK
TFWCURK QY KC PIZHVR QXVRLAGNTP
USAOEXAUFV CVE SWCQCZ QY KQN YPJSVZE : NBMHKTRWAWR BOAE OF EOVFJ VUGMGGCKOAC, TD E
EQCA QY LTEJ QGVGQS JR XGUEJ OW
QRPIINGWPTJ PL MY QSZ QYNGNL OWTRZDGAN. MPE RFLVR PILSYJGNTP WWG CUK OITDY WTKGUQR T'N
JSU EKP VEAE UT
BLHJECTFEG. BAX PIFVRV, TD ZROUZ QUFU UE PFZVDOTAYEGNK QSQVXIGY XAHFZNAPR, EOT CYJG
EKLFX NNSKAN WV SR XWVR QTGAN MPE
WPEQR OOSCFWZE, TP IYV ZOAELAV SR GGPBZTK QY K'GVROWV TDAIR UMZ ETSWGF, CU'OY XWEOLGJI
N X'AMR XW 6 CNJ.
OWYK ZOSF XW LOLPMWRE MUVHK EOEYMIF CUO BHL RU JPJZVD D'OAMHKRREASA MU VRLKQNELYI QQ
BKGB VCNJ WW VBYAT BHL GTV
AJSCASKF : FAUA CLFI, PTASCCGPNV OWW RFAZF-OFKS RF VIOGT JRM SPNVPK 1960 UHU FOG FS
WNV OW WCARZF CDNUJEJEGQD KA 1961,
YL FIRYS PNZNO, HHW LOLPMWR MMKECUCIEP FIR QN 1955 WHC DWTKL USAFRK FU LQXZNGQNZIK RN
XKT EFDPR OOTGLW NA TSSQCUOTAY VW
MFYVI FAVORNASUV YGRN SAVECFFATSNMYU A R'BFQOPZLVI Q'QCNRWK FE 1982, RF ESZQNZ BO
D'CUKPMV ROROIUAV SFY DMIDE.
OY S S GGRWWQRZT JRM JGSJPEFYMNIRM SXET UMHVF PUYAST. CVELI QQRTVYJG A VGGPHQ DGAM MP
UETNIEE ETPIJG PCFK QNECAYCF
SUV OSRF XA YRLAG, LVD ZSZYEY QIMVAEE VI FM RKRFDG CRASGVFE G WIMGR R FF LNGT TVPWCU.
EZLEZYETG, FW IRRYV QNUTXR
LMUSV RSVEK KGFJSTOM, W'MR QQS SRCDNELCK NBGEAEM VG TFFK PRE TKZJK, CVRTL IFFISR KM'KL
VESMG << UMVBMKKBCP >> IY'VX SUVN
TCTKF HEE VUJVN HQLXLJ. WRXOT PYLVE UPJRVQRK, TUJTY BLKTNDOB N XWELRCW UHQ << LKF
ZWOMVD FI FANZ CUK EAGLTPRE DK TYJGR
TP LCCQ DK CLWUSZZF >>. QNUS, ZBOL EODXW P'UQRUVHW FE CL KIEUE HRNZ JAIXGR, WGDOG
JGNGRC S GBZNA HHW CSTPFWVAN HECDNAEEW,
GHYURNHL NEJ DMGPQS, KG U XKNZ ASV OMTZEY DG JFFWYE DUYFY. KGLFY BIAZILRL KJAYLVI,
PTASCCGPNV LEIEUCGVHW, LUUTL TBXGGE
UNCIK NGQZQ BKGB ZCRDZF YA ETEYY VG JVF LVRE AMEYKUIW. NWTRZDGAN, MPE UTXJRDETPY
FQTRMDI RET WHY BWDZE HSYSAX N WGOMVYUI
N MPVEYFFRV L BSHQR G CUJVII OW 3 EAE, EZ DOW UOE AWVR XA VEIYTADXSMG BOAE XWXEETJ YAQ
CNNGHKOEYW. FRFH NNLEQN, VWDI,
PAMSRHUG DRYK PN EEXVY S LOLPJ EHJ ARRHLQUID VI QUX GAM, WV DVNGYIDE RRM WEHVNK TND
HGFUJF. UEP SYGDE JVZXGRVYUI RET
WHY BWDZE HSYSAX AY UQNJZEQNUT VNM VG SKFHISUATGM.
DG CYTXJEQ ET CIKKTZZF XEAIY RML NE TSAJSDE YVR Q. DOZNZYG'''


'''
keySize = 13

keysSets = []

uses = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

i = -1
for k in range(keySize):
    keysSets += [{}]
for item in text:
    if i == keySize-1 : i = 0
    else: i+=1
    if item in uses :
        if keysSets[i].get(item):
            keysSets[i][item] = keysSets[i][item] + 1
        else :
            keysSets[i][item] = 1
            


for i in range(keySize):
    print("Indice :", i, "\n",keysSets[i])
'''

def swap(S,i,j):
    S[i], S[j] = S[j], S[i]

def rc4_init(k):
    S = list(range(8))
    n = len(k)
    j=0
    for i in range(0,8):
        j=(j+S[i] + k[i%n])%8
        swap(S,i,j)
    return (S,0,0)

def rc4_getbits(st):
    (S,i,j)=st
    S=S.copy()
    i = (i+1)%8
    j = (S[i]+j)%8
    swap(S,i,j)
    t= (S[i]+S[j])%8
    return ((S,i,j),S[t])

k=[1,6,6,4]
res = rc4_init(k)
arr = '''0, 7, 1, 7, 2, 2, 3, 5, 4, 7, 7, 4, 5, 4, 5, 1, 7, 2, 5,
 6, 6, 3, 2, 5, 5, 7, 6, 1, 1, 2, 7, 1, 5, 5, 0, 4, 4, 7,
 6, 2, 4, 2, 0, 3, 1, 3, 1, 0, 4, 3, 1, 7, 1, 0, 3, 4, 0,
 5, 0, 4, 7, 7, 6, 6, 0, 2, 3, 5, 2, 1, 7, 0, 2, 1, 7, 4,
 0, 1, 6, 1, 3, 6, 0, 4, 5, 2, 1, 2, 6, 3, 1, 4, 2, 2, 4,
 3, 7, 7, 5, 2, 7, 1, 5, 4, 4, 7, 3, 5, 3, 2, 6, 6, 0, 7,
 6, 2, 5, 6, 2, 5, 4, 0, 0, 6, 5, 2, 0, 3, 3, 6, 0, 1, 1,
 5, 7, 7, 6, 7, 2, 2, 5, 4, 5, 1, 5, 3, 6, 0, 4, 4, 5, 7,
 1, 4, 5, 3, 6, 1, 1, 4, 2, 0, 2, 1, 4, 7, 7, 0, 7, 6, 0,
 7, 3, 3, 7, 7, 0, 3, 2, 1, 7, 7, 4, 0, 3, 6, 0, 1, 5, 0,
 2, 2, 7, 4, 2, 4, 6, 6, 4, 3, 1, 5, 1, 7, 1, 5, 5, 5, 0,
 2, 6, 5, 2, 2, 1, 3, 5, 2, 5, 6, 1, 5, 1, 2, 6, 2, 5, 2,
 6, 0, 1, 7, 4, 1, 2, 7, 4, 2, 0, 0, 5, 0, 1, 7, 1, 2, 4,
 6, 3, 3, 6, 5, 1, 7, 4, 5, 2, 3, 1, 5, 5, 6, 0, 4, 5, 3,
 6, 4, 0, 4, 2, 2, 1, 4, 7, 4, 0, 7, 2, 3, 5, 6, 0, 1, 1,
 4, 1, 1, 3, 2, 7, 3, 2, 2, 6, 6, 3, 3, 6, 2, 2, 4, 5, 5,
 0, 1, 0, 2, 6, 5, 6, 4, 4, 7, 4, 3, 4, 2, 6, 2, 3, 3, 2,
 5, 7, 5, 3, 2, 6, 1, 6, 6, 4, 2, 3, 5'''.replace("\n", "").split(", ")
res[0] = arr
print(rc4_getbits(res))


print(arr)